version: '3.8'

services:
  # Gmail MCP Server
  gmail-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmail-mcp-server
    ports:
      - "3002:3002"
    volumes:
      - ./gmail_mcp.py:/app/gmail_mcp.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    environment:
      # Gmail API Access Token
      - GMAIL_ACCESS_TOKEN=${GMAIL_ACCESS_TOKEN}

      # MCP Server Port
      - MCP_PORT=${MCP_PORT:-3002}

      # Optional: Log level
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
