version: '3.8'

services:
  gmail-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmail-mcp-server
    restart: unless-stopped
    environment:
      # Gmail API Access Token
      - GMAIL_ACCESS_TOKEN=${GMAIL_ACCESS_TOKEN}
      # Optional: Log level
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./gmail_mcp.py:/app/gmail_mcp.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    networks:
      - gmail-network
    stdin_open: true
    tty: true

  mcp-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: gmail-mcp-bridge
    restart: unless-stopped
    user: "0:0"
    ports:
      - "${MCP_PORT:-3002}:3002"
    depends_on:
      - gmail-mcp-server
    networks:
      - gmail-network
    environment:
      - PORT=3002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

networks:
  gmail-network:
    driver: bridge
